# Generated by Django 4.2.2 on 2023-06-25 17:34

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import students.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("welcome_pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("first_name", models.CharField(max_length=100, null=True)),
                ("last_name", models.CharField(max_length=100, null=True)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=12, null=True, region="FR"
                    ),
                ),
                ("birthdate", models.DateField(null=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        default="",
                        null=True,
                        upload_to="students/",
                        validators=[students.validators.validate_file_size],
                    ),
                ),
                (
                    "ongoing_degree",
                    models.CharField(blank=True, max_length=350, null=True),
                ),
                ("school", models.CharField(max_length=100, null=True)),
                (
                    "ongoing_year",
                    models.CharField(
                        choices=[
                            ["1ère année", "année 1"],
                            ["2ème année", "année 2"],
                            ["3ème année", "année 3"],
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("last_degree", models.CharField(max_length=350, null=True)),
                (
                    "experiences",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=100, null=True),
                            null=True,
                            size=3,
                        ),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "spoken_languages",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=100, null=True),
                            null=True,
                            size=2,
                        ),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "qualities",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100, null=True),
                        null=True,
                        size=5,
                    ),
                ),
                ("future_vision", models.CharField(max_length=300, null=True)),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("alternance", "Alternance ou Apprentissage"),
                            ("stage", "Stage"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "apprenticeship_rate",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "beginning_date",
                    models.DateField(default=datetime.date.today, null=True),
                ),
                (
                    "ending_date",
                    models.DateField(default=datetime.date.today, null=True),
                ),
                (
                    "demanded_jobs",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=150, null=True),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "demanded_domains",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=150, null=True),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "teleworking",
                    models.CharField(
                        choices=[
                            ("True", "Oui"),
                            ("False", "Non"),
                            ("None", "A définir"),
                        ],
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "work_weekend",
                    models.CharField(
                        choices=[
                            ("False", "Non"),
                            ("samedi", "Samedi"),
                            ("dimanche", "Dimanche"),
                            ("les_deux", "Les deux"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "overall_atmospheres",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("Sérieuse", "Sérieuse"),
                                ("Décontractée", "Décontractée"),
                                ("Coopérative", "Coopérative"),
                                ("Valorisante", "Valorisante"),
                                ("Conviviale", "Conviviale"),
                            ],
                            max_length=80,
                            null=True,
                        ),
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "company_sizes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("petite", "Petite"),
                                ("moyenne", "Moyenne"),
                                ("grande", "Grande"),
                                ("familiale", "Familiale"),
                                ("start-up", "Start-up"),
                            ],
                            max_length=80,
                            null=True,
                        ),
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "company_locations",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200, null=True),
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "company_values",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100, null=True),
                        default=list,
                        null=True,
                        size=5,
                    ),
                ),
                (
                    "autonomy",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("faible", "Faible"),
                                ("moyen", "Moyen"),
                                ("important", "Important"),
                            ],
                            max_length=80,
                            null=True,
                        ),
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "hiring",
                    models.CharField(
                        choices=[
                            ("oui", "Oui"),
                            ("non", "Non"),
                            ("pourquoi_pas", "Pourquoi pas"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Étudiant",
                "verbose_name_plural": "Étudiants",
                "ordering": ["-user__date_joined", "user__email"],
            },
        ),
    ]
