# Generated by Django 4.2.2 on 2023-06-30 09:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={
                "ordering": ["-user__date_joined"],
                "verbose_name": "Étudiant",
                "verbose_name_plural": "Étudiants",
            },
        ),
    ]
