# Generated by Django 4.2.2 on 2023-06-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("offer_id", models.CharField(max_length=200, unique=True)),
                ("price_id", models.CharField(max_length=200, unique=True)),
                ("price", models.IntegerField()),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Offre",
                "verbose_name_plural": "Offres du site",
                "ordering": ["price"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ["Payement initialisé", "initialised"],
                            ["Payement reçu", "success"],
                            ["Payement en attente", "waiting"],
                            ["Payement échoué", "error"],
                        ],
                        default="initialised",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Achat",
                "verbose_name_plural": "Achats des entreprises du site",
                "ordering": ["-date"],
            },
        ),
    ]
