# Generated by Django 4.2.2 on 2023-06-24 16:26

import os
from django.db import migrations
from welcome_pages.models import User


# pylint: disable=unused-argument
def create_superusers(apps, schema_editor):
    emails = ["antoine.cheneau@student-cs.fr"]
    for email in emails:
        super_user = User.objects.create_user(
            email=email,
            password=os.getenv("SUPERUSER_PASSWORD"),
        )
        super_user.is_superuser = True
        super_user.is_staff = True
        super_user.save()


class Migration(migrations.Migration):
    dependencies = [
        ("welcome_pages", "0001_initial"),
        ("data_management", "0001_initial"),
        ("students", "0001_initial"),
        ("companies", "0001_initial"),
        ("matching", "0001_initial"),
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_superusers),
    ]
