# Generated by Django 4.2.2 on 2023-06-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="engagement",
            field=models.BooleanField(default=False),
        ),
    ]
