# Generated by Django 4.2.2 on 2023-07-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0003_alter_company_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="stripe_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
