# Generated by Django 4.2.2 on 2023-06-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat", models.CharField(max_length=2000)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("by", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages échangés",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_liked", models.BooleanField(default=False)),
                ("company_liked", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Like",
                "verbose_name_plural": "Likes des utilisateurs",
                "ordering": ["-student_liked", "-company_liked"],
            },
        ),
    ]
