# Generated by Django 4.2.2 on 2023-06-25 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("students", "0001_initial"),
        ("matching", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="companies.job"
            ),
        ),
        migrations.AddField(
            model_name="like",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="students.student"
            ),
        ),
        migrations.AddField(
            model_name="chats",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="companies.job"
            ),
        ),
        migrations.AddField(
            model_name="chats",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="students.student"
            ),
        ),
    ]
